<?php


// Get our resume, that comes from our xml file
/** @var $resume RussellAlbin\Resume\Api\Data\ResumeInterface */
$resume = $block->getResumeData();

?>
<h1>Some Personal Information</h1>
<div>Name: <?= $resume->getFirstname() . ' ' . $resume->getLastname(); ?></div>
<div>Email: <?= $resume->getEmail(); ?></div>
<div>Cell Phone: <?= $resume->getPhone(); ?></div>
<div>Magento URL: <?php /* $xml->personal_information->magento_url; */ ?></div>
<div>LinkedIn URL: <?php /* $xml->personal_information->linkedin_url; */ ?></div>
<div>Skills: <?= $resume->getSkills(); ?></div>
<div>Objective: <?= $resume->getObjective(); ?></div>
<hr>
<h2>Certifications</h2>

    <?php /* foreach($xml->certifications as $_certification): ?>
        <?php foreach($_certification as $_items): ?>
        <div>
                <h4><?php echo $_items->title; ?></h4>
                <ul>
                <?php foreach($_items as $_item): ?>
                    <?php foreach($_item as $_cert): ?>
                        <li>
                            <div>Name: <?php echo $_cert->name; ?></div>
                            <div>Date Certified: <?php echo date("F Y", strtotime($_cert->date_certified)); ?></div>
                            <?php if(strlen($_cert->template_image)): ?>
                                <div><img class="image-testing" src="<?php echo $block->getViewFileUrl('RussellAlbin_Resume::images/' . $_cert->template_image) ?>"></div>
                            <?php endif; ?>
                            <hr>
                        </li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
                </ul>
        </div>
        <?php endforeach; ?>

    <?php endforeach; */ ?>


